# Generated by Django 5.0.1 on 2024-02-02 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_incident_acknowledge_incident_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='call',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
