# Generated by Django 5.0.1 on 2024-02-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_location_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='acknowledge',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='call',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
