# Generated by Django 5.0.1 on 2024-02-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_incident_acknowledge_alter_incident_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='serial_number',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
