# Generated by Django 5.0.1 on 2024-02-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='serial_number',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
