# Generated by Django 5.0.1 on 2024-02-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_location_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
