"""
Django settings for sparkontrol project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ntotcnj6ju09gmhr7j9dfg=bn+sxs_k-%wz0yk$(g4%zm%l&%h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'import_export',
    'rangefilter',
    'auditlog',
    'portal',
    'schedules',
    'baton.autodiscover',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'django_auto_logout.middleware.auto_logout',
]

AUTO_LOGOUT = {
    'IDLE_TIME': 600,
    'SESSION_TIME': 1200,
    'MESSAGE': 'The session has expired. Please login again to continue.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}
APPEND_SLASH  = True

ROOT_URLCONF = 'sparkontrol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR,
            os.path.join(BASE_DIR, 'templates') 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FileUploadParser',
    ],
}

WSGI_APPLICATION = 'sparkontrol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

FIREBASE_CONFIG  = {
  "type": "service_account",
  "project_id": "sparkontrol-b9de9",
  "private_key_id": "7d1d12d2ee48982fec9a41e7ab1f57094bb919ac",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDBCCS+BGqC5+Tq\nWnzkf5CQHRhd5ZR3+KkWkD8E+O0Ud+W8Bu/xFJSLV+Py3rdl7b/sVI3Hobon+evm\nov016x8Og2DSzWdNVpXZTyTvgN8d0A2pY0xIhUtVfhYLpigxp+Mar2n+Dl6i2lu+\n0ZCdppQs75SOW0bls7f7wmYt94+8nUiBfxNWui0yKxgRm161xon5wpY2Lta7cQ/u\nOa5S3xFSZ2jX+eHCS9gjVWjGAQrYp2twGn0PGhCeGzQ7qx0QjgGgG/gYVEkFxMrW\nYqItxPr08PDzzjUxQ3pw0NNrRgQlTUxD2XRN/T5ytHU4FGnFgoBFHtcf4QoTP46/\nVPXxDrN7AgMBAAECggEAFDHuaiTbIdvyAqS56UwBS1qH6JbyzARraE1qEnKalyge\nFGhjZQUCr3tgAVJUvKi9ihOki6y7ZaBLkmMd+6ygIKwVDqjntFspLUWO9zGz5hIU\nw9J8MiAj7AtXchuNm/hVFb8hZy+IriALNjEFoMDDQtpD4ArjpXeCeafyeb+rPY/G\nSHyrfFQG3zSJOVebfvXgrAElsqjSeZPj32lOjaXgcHmFOF1VDwHh23UWIJ8sZZAz\nKViw4dvycOrw16kB7dtp0rxQOl4rPYRpiqQRBRnvIGpqoSB+BEKX0tEfbDIcLZiM\nbUUxp2hcHYkL9NXs8AjdyBMwnnkIIWl6Hc94KFIj1QKBgQDzSZnXhSti8VboBwxI\nXvcb/ql4X4XVCoIGdXDEurvoMIiDl28MsvkwZm8l3S424azhskct7ryPoCfJkp7Y\nfwSx61NsoLJjpJeVRaIsmQyD3l1ig2xO1oRIZLTO+dHYCjFnqcltMN6ZjwuXyup/\nZwOU/8euJZBYvxjk7T0k7yBEFwKBgQDLHki8wuvYOirsfBtGQiYoe5S2bDZNhqeh\n1QmUyQ0cKc5nbmidrTj4+FxHqYH5cS2zJXWVyNXd2o9YHmv/A9lWDEIrv2EE7Bns\nLYs2AjsxDMYb2cLW7MkpS5C99UBo05m3niC4Xde0CIYRPFThR3KWCHa9YrjXBbiT\nG/Esi++WPQKBgF+oCL0ctzpn+euxGbs6254+OxQBOvXQ897mPjib01Yv/vz+hcNQ\ne3n0TK9uj8U0Zm03U5VT0QAH0J0I8TvedVIfXOXRKVLUXGVsw58Vbj5LKByb3/H/\nlnOAZTccMs3m9BX2RCSSmnN2MvCz8A+3yUjEaRan3mGGgZtBTFFBVEZxAoGANRmk\nsFxQ5cVHJW3If5SZfynXld0yURAr0L3t9EyfNcakJBwUE2yOoV/kWAOza++vn87i\nL5dCee5CXSoO16s87SblQaSVi4DhwgGiDCuHJ+qL/Anwytk6OaZ8n3x3KzBuVjdr\nnGdEFdfInMbl9cME7L4ntJkTc3sWZrb+VMP8jY0CgYEAwmc/ARr+8l0A90mU/alU\nmP5B9Z0Atct/FFWHIQtfIhLlkIzka6qBXFrS5g4d/aL4lXeGZmi1vDGNSm3U+KPY\nThrJr8yMtoalnVv/Ut+KxgHYL8mPWTuaOTJoALmWUK4zJwrKfL9SU0OLq7qX+W+Q\nrgO1UIqS8jd7KzyHn3ZPhq8=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-774h0@sparkontrol-b9de9.iam.gserviceaccount.com",
  "client_id": "111815314770642439609",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-774h0%40sparkontrol-b9de9.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
   os.path.join(BASE_DIR, 'static'),
]

#STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




THUMBNAILS = {
    'METADATA': {
        'BACKEND': 'thumbnails.backends.metadata.DatabaseBackend',
    },
    'STORAGE': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        # You can also use Amazon S3 or any other Django storage backends
    },
    'SIZES': {
        'small': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 10, 'height': 10},
                {'PATH': 'thumbnails.processors.crop', 'width': 80, 'height': 80}
            ],
            'POST_PROCESSORS': [
                {
                    'PATH': 'thumbnails.post_processors.optimize',
                    'png_command': 'optipng -force -o7 "%(filename)s"',
                    'jpg_command': 'jpegoptim -f --strip-all "%(filename)s"',
                },
            ],
        },
        'large': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 20, 'height': 20},
                {'PATH': 'thumbnails.processors.flip', 'direction': 'horizontal'}
            ],
        },
        'watermarked': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 20, 'height': 20},
                # Only supports PNG. File must be of the same size with thumbnail (20 x 20 in this case)
                {'PATH': 'thumbnails.processors.add_watermark', 'watermark_path': 'watermark.png'}
            ],
        }
    }
}

BATON = {
    'SITE_HEADER': 'Sparkontrol',
    'SITE_TITLE': 'Sparkontrol',
    'INDEX_TITLE': 'Site administration',
    'SUPPORT_HREF': 'https://www.sparkontrol.com/',
    'COPYRIGHT': 'copyright © 2023 <a href="https://www.sparkontrol.com/">Sparkontrol</a>', # noqa
    'POWERED_BY': '<a href="https://www.sparkontrol.com/">Sparkontrol Instruments</a>',
    'CONFIRM_UNSAVED_CHANGES': True,
    'SHOW_MULTIPART_UPLOADING': True,
    'ENABLE_IMAGES_PREVIEW': True,
    'COLLAPSABLE_USER_AREA': True,
    'CHANGELIST_FILTERS_IN_MODAL': True,
    'CHANGELIST_FILTERS_ALWAYS_OPEN': True,
    'CHANGELIST_FILTERS_FORM': True,
    'MENU_ALWAYS_COLLAPSED': False,
    'MENU_TITLE': 'Menu',
    'MESSAGES_TOASTS': True,
    'GRAVATAR_DEFAULT_IMG': '',
    'GRAVATAR_ENABLED': True,
    'LOGIN_SPLASH': '/static/images/gradient.png',
    'MENU': (
        { 'type': 'title', 'label': 'main', 'apps': ('auth',) },
        {
            'type': 'app',
            'name': 'auth',
            'label': 'Authentication',
            'icon': 'fa fa-lock',
            'models': (
                {
                    
                    'icon': 'fa fa-user',
                    'name': 'user',
                    'label': 'Users'
                },
                {
                    
                    'icon': 'fa fa-users',
                    'name': 'group',
                    'label': 'Groups'
                },
            )
        },
        { 'type': 'title', 'label': 'Portal', 'apps': ('portal','auditlog' ) },
        {
            'type': 'app',
            'name': 'portal',
            'label': 'Portal',
            'icon': 'fa fa-lock',
            'models': (
                {
                    'icon': 'fa fa-mobile-alt',
                    'name': 'location',
                    'label': 'Locations'
                },
                {
                    'icon': 'fa fa-box',
                    'name': 'remote',
                    'label': 'Remotes'
                },
                {
                    'icon': 'fa fa-database',
                    'name': 'incident',
                    'label': 'Incidents'
                },
                {
                    'icon': 'fa fa-database',
                    'name': 'subscription',
                    'label': 'Subscription'
                },
            )
        },
        {
            'type': 'app',
            'name': 'auditlog',
            'label': 'Audit Log',
            'icon': 'fa fa-lock',
            'models': (
                {
                    'icon': 'fa fa-clipboard-check',
                    'name': 'logentry',
                    'label': 'Log Entries'
                },
            )
        },
        # { 'type': 'title', 'label': 'Contents', 'apps': ('portal', ) },
        # { 'type': 'model', 'label': 'Pages', 'name': 'device', 'app': 'portal' },
        # { 'type': 'free', 'label': 'Custom Link', 'url': 'http://www.google.it', 'perms': ('flatpages.add_flatpage', 'auth.change_user') },
        # { 'type': 'free', 'label': 'My parent voice', 'children': [
        #     { 'type': 'model', 'label': 'A Model', 'name': 'profile', 'app': 'portal' },
        #     { 'type': 'free', 'label': 'Another custom link', 'url': 'http://www.google.it' },
        # ] },
    )
}